# Site
name: 'Ken Hughes'
description: 'Ken Hughes - Technology, Productivity and Automating Everything...'
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
# email: 'wowthemesnet@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ken:
      name:           Ken
      site:           https://kapie.com
      avatar:         assets/images/shrek.jpg
      bio:            "Hi, I'm Ken, the author of the site you are currently viewing. I hope you like it!"
      email:          ken@kapie.com
      twitter:        https://twitter.com/kjhughes
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ken
      avatar: /assets/images/shrek.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]